# Generated by Django 2.2.7 on 2019-11-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimBolsaAuxilio',
            fields=[
                ('codBolsaAuxilio', models.AutoField(primary_key=True, serialize=False)),
                ('codOriginalBolsaAuxilio', models.IntegerField(blank=True, null=True)),
                ('descricaoBolsaAuxilio', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimCurso',
            fields=[
                ('codCurso', models.AutoField(primary_key=True, serialize=False)),
                ('codOriginalCurso', models.IntegerField()),
                ('nomeCurso', models.CharField(max_length=255)),
                ('quantidadeIngresso', models.IntegerField(blank=True, null=True)),
                ('quantidadeConcluinte', models.IntegerField(blank=True, null=True)),
                ('grauAcademico', models.CharField(blank=True, max_length=255, null=True)),
                ('turno', models.IntegerField(blank=True, null=True)),
                ('capital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DimDeficiencia',
            fields=[
                ('codDeficiencia', models.AutoField(primary_key=True, serialize=False)),
                ('codOriginalDeficiencia', models.IntegerField(blank=True, null=True)),
                ('descricaoDeficiencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimLocalIES',
            fields=[
                ('codLocalIES', models.AutoField(primary_key=True, serialize=False)),
                ('codOriginalLocalIES', models.IntegerField(blank=True, null=True)),
                ('nomeRegiao', models.CharField(blank=True, max_length=3, null=True)),
                ('categoriaAdmistrativa', models.IntegerField(blank=True, null=True)),
                ('nomeUF', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimReservaVagas',
            fields=[
                ('codReservaVagas', models.AutoField(primary_key=True, serialize=False)),
                ('codOriginalReservaVagas', models.IntegerField(blank=True, null=True)),
                ('descricaoReservaVagas', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimTempo',
            fields=[
                ('codTempo', models.AutoField(primary_key=True, serialize=False)),
                ('codOriginalTempo', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indiceEscolaPublicaCursosTradicionais', models.IntegerField(blank=True, null=True)),
                ('indiceIngressantesConcluintesRegiao', models.IntegerField(blank=True, null=True)),
                ('indiceDesistenciaReservaVagasRegiao', models.IntegerField(blank=True, null=True)),
                ('indiceDesistenciaDeficiencia', models.IntegerField(blank=True, null=True)),
                ('indiceConcluintesCapitalInteriorNordeste', models.IntegerField(blank=True, null=True)),
                ('indiceConcluintesBolsistaNordeste', models.IntegerField(blank=True, null=True)),
                ('indiceBaixaRendaNoturnoRegiao', models.IntegerField(blank=True, null=True)),
                ('indiceDesistenciaLicenciaturaIngresso', models.IntegerField(blank=True, null=True)),
                ('codBolsaAuxilioPk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.DimBolsaAuxilio')),
                ('codCursoPk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.DimCurso')),
                ('codDeficienciaPk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.DimDeficiencia')),
                ('codLocalIESPk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.DimLocalIES')),
                ('codReservaVagasPk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.DimReservaVagas')),
                ('codTempoPk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.DimTempo')),
            ],
            options={
                'unique_together': {('codLocalIESPk', 'codTempoPk', 'codCursoPk', 'codReservaVagasPk', 'codDeficienciaPk', 'codBolsaAuxilioPk')},
            },
        ),
    ]
