# Generated by Django 2.2.7 on 2019-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191121_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimcurso',
            name='grauAcademico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
