# Generated by Django 2.2.7 on 2019-11-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20191121_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimcurso',
            name='grauAcademico',
        ),
    ]
