# Generated by Django 2.2.7 on 2019-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_dimcurso_grauacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimcurso',
            name='grauAcademico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
