# Generated by Django 2.2.7 on 2019-11-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_dimcurso_grauacademico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimbolsaauxilio',
            name='descricaoBolsaAuxilio',
        ),
        migrations.RemoveField(
            model_name='dimdeficiencia',
            name='descricaoDeficiencia',
        ),
        migrations.RemoveField(
            model_name='dimreservavagas',
            name='descricaoReservaVagas',
        ),
    ]
