# Generated by Django 2.2.7 on 2019-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20191121_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimlocalies',
            name='nomeRegiao',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
