# Generated by Django 2.2.7 on 2019-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20191121_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiao',
            new_name='indiceIngressantesConcluintesRegiaoEstadual',
        ),
        migrations.AddField(
            model_name='fatoaluno',
            name='indiceIngressantesConcluintesRegiaoFederal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
