# Generated by Django 2.2.7 on 2019-11-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20191124_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatoaluno',
            name='indiceDesistenciaReservaVagasRegiao',
        ),
    ]
