# Generated by Django 2.2.7 on 2019-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_fatoaluno_indicedesistenciareservavagasregiao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiaoEstadual',
            new_name='indiceIngressantesConcluintesRegiaoConcluinteEstadual',
        ),
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiaoFederal',
            new_name='indiceIngressantesConcluintesRegiaoConcluinteFederal',
        ),
        migrations.AddField(
            model_name='fatoaluno',
            name='indiceIngressantesConcluintesRegiaoIngressanteEstadual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatoaluno',
            name='indiceIngressantesConcluintesRegiaoIngressanteFederal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
