# Generated by Django 2.2.7 on 2019-11-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_fatoaluno_indicedesistenciaresevavagasregiao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceDesistenciaResevaVagasRegiao',
            new_name='indiceDesistenciaReservaVagasRegiao',
        ),
    ]
