# Generated by Django 2.2.7 on 2019-11-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20191126_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiaoConcluinteEstadual',
            new_name='indiceIngressantesRegiaoConcluinteEstadual',
        ),
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiaoConcluinteFederal',
            new_name='indiceIngressantesRegiaoConcluinteFederal',
        ),
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiaoIngressanteEstadual',
            new_name='indiceIngressantesRegiaoIngressanteEstadual',
        ),
        migrations.RenameField(
            model_name='fatoaluno',
            old_name='indiceIngressantesConcluintesRegiaoIngressanteFederal',
            new_name='indiceIngressantesRegiaoIngressanteFederal',
        ),
    ]
