# Generated by Django 2.2.7 on 2019-11-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idaluno', models.AutoField(db_column='idAluno', primary_key=True, serialize=False)),
                ('codigoalunocurso', models.IntegerField(blank=True, null=True)),
                ('codigoaluno', models.BigIntegerField(blank=True, db_column='codigoAluno', null=True)),
                ('idadealuno', models.IntegerField(blank=True, db_column='idadeAluno', null=True)),
                ('quantidadecargahorariatotal', models.IntegerField(blank=True, db_column='quantidadeCargahorariaTotal', null=True)),
                ('quantidadecargahorariaintegral', models.IntegerField(blank=True, db_column='quantidadeCargaHorariaIntegral', null=True)),
                ('dataingressocurso', models.CharField(blank=True, db_column='dataIngressoCurso', max_length=10, null=True)),
                ('inatividadeextracurricular', models.IntegerField(blank=True, db_column='inatividadeExtraCurricular', null=True)),
                ('incomplestagio', models.CharField(blank=True, max_length=10, null=True)),
                ('incomplextensao', models.CharField(blank=True, max_length=10, null=True)),
                ('incomplmonitoria', models.CharField(blank=True, max_length=10, null=True)),
                ('incomplpesquisa', models.CharField(blank=True, max_length=10, null=True)),
                ('inbolsaestagio', models.CharField(blank=True, max_length=10, null=True)),
                ('inbolsaextensao', models.CharField(blank=True, max_length=10, null=True)),
                ('inbolsamonitoria', models.CharField(blank=True, max_length=10, null=True)),
                ('inbolsapesquisa', models.CharField(blank=True, max_length=10, null=True)),
                ('codigotipoescolaensinomedio', models.IntegerField(blank=True, null=True)),
                ('inalunoparfor', models.CharField(blank=True, max_length=10, null=True)),
                ('inconcluente', models.IntegerField(blank=True, null=True)),
                ('iningressototal', models.IntegerField(blank=True, null=True)),
                ('iningressovaganova', models.IntegerField(blank=True, null=True)),
                ('anoingresso', models.IntegerField(blank=True, db_column='anoIngresso', null=True)),
                ('fkcodigocurso', models.IntegerField(blank=True, db_column='fkCodigoCurso', null=True)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apoiosocial',
            fields=[
                ('idapoiosocial', models.AutoField(db_column='idApoioSocial', primary_key=True, serialize=False)),
                ('alimentacao', models.IntegerField(blank=True, null=True)),
                ('permanencia', models.IntegerField(blank=True, null=True)),
                ('trabalho', models.IntegerField(blank=True, null=True)),
                ('materialdidatico', models.IntegerField(blank=True, db_column='materialDidatico', null=True)),
                ('moradia', models.IntegerField(blank=True, null=True)),
                ('transporte', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apoiosocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriaadministrativa',
            fields=[
                ('idcategoriaadministrativa', models.AutoField(db_column='idCategoriaAdministrativa', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categoriaAdministrativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigocurso', models.AutoField(primary_key=True, serialize=False)),
                ('nomecurso', models.CharField(blank=True, max_length=300, null=True)),
                ('incapitalcurso', models.CharField(blank=True, max_length=68, null=True)),
                ('codigomodalidadeensino', models.CharField(blank=True, max_length=15, null=True)),
                ('descricaomodalidadeensio', models.CharField(blank=True, max_length=29, null=True)),
                ('numerocargahoraria', models.CharField(blank=True, max_length=10, null=True)),
                ('codigoturno', models.IntegerField(blank=True, null=True)),
                ('quantidadematriculacurso', models.IntegerField(blank=True, null=True)),
                ('quantidadeconcluintecurso', models.IntegerField(blank=True, null=True)),
                ('quantidadeingressocurso', models.IntegerField(blank=True, null=True)),
                ('quantidadeingressovagasnovas', models.IntegerField(blank=True, null=True)),
                ('codigooriginal', models.IntegerField(blank=True, db_column='codigoOriginal', null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('iddeficiencia', models.AutoField(db_column='idDeficiencia', primary_key=True, serialize=False)),
                ('auditiva', models.IntegerField(blank=True, null=True)),
                ('fisica', models.IntegerField(blank=True, null=True)),
                ('intelectual', models.IntegerField(blank=True, null=True)),
                ('multipla', models.IntegerField(blank=True, null=True)),
                ('surdez', models.IntegerField(blank=True, null=True)),
                ('surdocegueira', models.IntegerField(blank=True, db_column='surdoCegueira', null=True)),
                ('baixavisao', models.IntegerField(blank=True, db_column='baixaVisao', null=True)),
                ('cegueira', models.IntegerField(blank=True, null=True)),
                ('superdotacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deficiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('codigoetnia', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'etnia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grauacademico',
            fields=[
                ('idgrauacademico', models.AutoField(db_column='idGrauAcademico', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'grauAcademico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ies',
            fields=[
                ('idcodigoies', models.AutoField(db_column='idCodigoIES', primary_key=True, serialize=False)),
                ('nomeies', models.CharField(blank=True, db_column='nomeIES', max_length=97, null=True)),
                ('siglaies', models.CharField(blank=True, db_column='siglaIES', max_length=60, null=True)),
            ],
            options={
                'db_table': 'ies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('codigolocaloferta', models.AutoField(primary_key=True, serialize=False)),
                ('codigomunicipio', models.IntegerField(blank=True, null=True)),
                ('nomemunicipio', models.CharField(blank=True, max_length=200, null=True)),
                ('codigouf', models.IntegerField(blank=True, null=True)),
                ('siglauf', models.CharField(blank=True, max_length=2, null=True)),
                ('nomeregiao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidadeensino',
            fields=[
                ('idmodalidadeensino', models.AutoField(db_column='idModalidadeEnsino', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'modalidadeEnsino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacaoacademica',
            fields=[
                ('idorganizacaoacademica', models.AutoField(db_column='idOrganizacaoAcademica', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'organizacaoAcademica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservavagas',
            fields=[
                ('idreservavagas', models.AutoField(db_column='idReservaVagas', primary_key=True, serialize=False)),
                ('deficiencia', models.IntegerField(blank=True, null=True)),
                ('ensinopublico', models.IntegerField(blank=True, db_column='ensinoPublico', null=True)),
                ('etnico', models.IntegerField(blank=True, null=True)),
                ('rendafamiliar', models.IntegerField(blank=True, db_column='rendaFamiliar', null=True)),
                ('outro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservaVagas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('codigosexo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('codigosituacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'situacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('codigotempo', models.IntegerField(primary_key=True, serialize=False)),
                ('ano', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tempo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('codigoturno', models.AutoField(primary_key=True, serialize=False)),
                ('integral', models.CharField(blank=True, max_length=1, null=True)),
                ('matutino', models.CharField(blank=True, max_length=1, null=True)),
                ('vespertino', models.CharField(blank=True, max_length=1, null=True)),
                ('noturno', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alunocurso',
            fields=[
                ('idaluno', models.ForeignKey(db_column='idaluno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='normalized.Aluno')),
            ],
            options={
                'db_table': 'alunocurso',
                'managed': False,
            },
        ),
    ]
